apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  creationTimestamp: "2021-11-29T05:37:24Z"
  labels:
    app.kubernetes.io/instance: linuxsuren
  name: cgit-v0.0.13
  namespace: linuxsuren-bot
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/LinuxSuRen/linuxsuren-versions
      branch: master
      name: linuxsuren-versions
      provider: github
    secret: {}
  phase: draft
  repositories:
  - action: release
    address: https://github.com/LinuxSuRen/cgit
    branch: master
    name: cgit
    provider: github
    version: v0.0.13
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.13
status: {}
