apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"devops.kubesphere.io/v1alpha1","kind":"Releaser","metadata":{"annotations":{},"creationTimestamp":"2021-11-29T05:37:24Z","labels":{"app.kubernetes.io/instance":"linuxsuren"},"name":"cgit-v0.0.13","namespace":"linuxsuren-bot"},"spec":{"gitOps":{"enable":true,"repository":{"address":"https://github.com/LinuxSuRen/linuxsuren-versions","branch":"master","name":"linuxsuren-versions","provider":"github"},"secret":{}},"phase":"ready","repositories":[{"action":"release","address":"https://github.com/LinuxSuRen/cgit","branch":"master","name":"cgit","provider":"github","version":"v0.0.13"}],"secret":{"name":"linuxsuren-bot","namespace":"ks-releaser-system"},"version":"v0.0.13"},"status":{}}
    releaser.devops.kubesphere.io/hash: fd57fd58c
  creationTimestamp: "2022-01-18T02:21:07Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: linuxsuren
  name: cgit-v0.0.13
  namespace: linuxsuren-bot
  selfLink: /apis/devops.kubesphere.io/v1alpha1/namespaces/linuxsuren-bot/releasers/cgit-v0.0.13
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/LinuxSuRen/linuxsuren-versions
      branch: master
      name: linuxsuren-versions
      provider: github
    secret: {}
  phase: done
  repositories:
  - action: release
    address: https://github.com/LinuxSuRen/cgit
    branch: master
    name: cgit
    provider: github
    version: v0.0.13
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.13
status:
  conditions:
  - conditionType: release
    message: https://github.com/LinuxSuRen/cgit was released
    status: success
