apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"devops.kubesphere.io/v1alpha1","kind":"Releaser","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"linuxsuren"},"name":"cobra-extension-v0.0.12","namespace":"linuxsuren-bot"},"spec":{"gitOps":{"enable":true,"repository":{"address":"https://github.com/LinuxSuRen/linuxsuren-versions","branch":"master","name":"linuxsuren-versions","provider":"github"},"secret":{}},"phase":"ready","repositories":[{"action":"release","address":"https://github.com/LinuxSuRen/cobra-extension","branch":"master","name":"cobra-extension","provider":"github","version":"v0.0.12"}],"secret":{"name":"linuxsuren-bot","namespace":"ks-releaser-system"},"version":"v0.0.12"},"status":{}}
    releaser.devops.kubesphere.io/hash: 59455c9989
  creationTimestamp: "2021-12-08T11:28:58Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: linuxsuren
  name: cobra-extension-v0.0.12
  namespace: linuxsuren-bot
  selfLink: /apis/devops.kubesphere.io/v1alpha1/namespaces/linuxsuren-bot/releasers/cobra-extension-v0.0.12
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/LinuxSuRen/linuxsuren-versions
      branch: master
      name: linuxsuren-versions
      provider: github
    secret: {}
  phase: done
  repositories:
  - action: release
    address: https://github.com/LinuxSuRen/cobra-extension
    branch: master
    name: cobra-extension
    provider: github
    version: v0.0.12
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.12
status:
  conditions:
  - conditionType: release
    message: https://github.com/LinuxSuRen/cobra-extension was released
    status: success
