apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  creationTimestamp: "2021-11-14T14:12:09Z"
  labels:
    app.kubernetes.io/instance: linuxsuren
  name: go-cli-alias-v0.0.10
  namespace: linuxsuren-bot
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/LinuxSuRen/linuxsuren-versions
      branch: master
      name: linuxsuren-versions
      provider: github
    secret: {}
  phase: draft
  repositories:
  - action: release
    address: https://github.com/LinuxSuRen/go-cli-alias
    branch: master
    name: go-cli-alias
    provider: github
    version: v0.0.10
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.10
status: {}
