apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  name: goget-v0.0.9
  namespace: linuxsuren-bot
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/LinuxSuRen/linuxsuren-versions
      branch: master
      name: linuxsuren-versions
      provider: github
    secret: {}
  phase: ready
  repositories:
  - action: release
    address: https://github.com/LinuxSuRen/goget
    branch: master
    name: goget
    provider: github
    version: v0.0.9
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.9
status: {}
