apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"devops.kubesphere.io/v1alpha1","kind":"Releaser","metadata":{"annotations":{},"creationTimestamp":"2021-11-21T15:00:40Z","labels":{"app.kubernetes.io/instance":"linuxsuren"},"name":"goplay-v0.0.5","namespace":"linuxsuren-bot"},"spec":{"gitOps":{"enable":true,"repository":{"address":"https://github.com/LinuxSuRen/linuxsuren-versions","branch":"master","name":"linuxsuren-versions","provider":"github"},"secret":{}},"phase":"ready","repositories":[{"action":"release","address":"https://github.com/LinuxSuRen/goplay","branch":"master","name":"goplay","provider":"github","version":"v0.0.5"}],"secret":{"name":"linuxsuren-bot","namespace":"ks-releaser-system"},"version":"v0.0.5"},"status":{}}
    releaser.devops.kubesphere.io/hash: 7bf76c4cc
  creationTimestamp: "2021-11-28T15:02:08Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: linuxsuren
  name: goplay-v0.0.5
  namespace: linuxsuren-bot
  selfLink: /apis/devops.kubesphere.io/v1alpha1/namespaces/linuxsuren-bot/releasers/goplay-v0.0.5
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/LinuxSuRen/linuxsuren-versions
      branch: master
      name: linuxsuren-versions
      provider: github
    secret: {}
  phase: done
  repositories:
  - action: release
    address: https://github.com/LinuxSuRen/goplay
    branch: master
    name: goplay
    provider: github
    version: v0.0.5
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.5
status:
  conditions:
  - conditionType: release
    message: https://github.com/LinuxSuRen/goplay was released
    status: success
