apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"devops.kubesphere.io/v1alpha1","kind":"Releaser","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"linuxsuren"},"name":"goplay-v0.0.1","namespace":"linuxsuren-bot"},"spec":{"gitOps":{"enable":true,"repository":{"address":"https://github.com/LinuxSuRen/linuxsuren-versions","branch":"master","name":"linuxsuren-versions","provider":"github"}},"phase":"ready","repositories":[{"action":"release","address":"https://github.com/LinuxSuRen/goplay","branch":"master","name":"goplay","provider":"github","version":"v0.0.1"}],"secret":{"name":"linuxsuren-bot","namespace":"ks-releaser-system"},"version":"v0.0.1"}}
    releaser.devops.kubesphere.io/hash: 79778d8d49
  creationTimestamp: "2021-11-18T10:41:40Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: linuxsuren
  name: goplay-v0.0.1
  namespace: linuxsuren-bot
  selfLink: /apis/devops.kubesphere.io/v1alpha1/namespaces/linuxsuren-bot/releasers/goplay-v0.0.1
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/LinuxSuRen/linuxsuren-versions
      branch: master
      name: linuxsuren-versions
      provider: github
    secret: {}
  phase: done
  repositories:
  - action: release
    address: https://github.com/LinuxSuRen/goplay
    branch: master
    name: goplay
    provider: github
    version: v0.0.1
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.1
status:
  conditions:
  - conditionType: release
    message: https://github.com/LinuxSuRen/goplay was released
    status: success
