apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"devops.kubesphere.io/v1alpha1","kind":"Releaser","metadata":{"annotations":{},"creationTimestamp":"2021-11-26T14:09:09Z","labels":{"app.kubernetes.io/instance":"linuxsuren"},"name":"http-downloader-v0.0.53","namespace":"linuxsuren-bot"},"spec":{"gitOps":{"enable":true,"repository":{"address":"https://github.com/LinuxSuRen/linuxsuren-versions","branch":"master","name":"linuxsuren-versions","provider":"github"},"secret":{}},"phase":"ready","repositories":[{"action":"release","address":"https://github.com/LinuxSuRen/http-downloader","branch":"master","name":"http-downloader","provider":"github","version":"v0.0.53"}],"secret":{"name":"linuxsuren-bot","namespace":"ks-releaser-system"},"version":"v0.0.53"},"status":{}}
    releaser.devops.kubesphere.io/hash: 78c6df5b67
  creationTimestamp: "2021-11-26T15:04:23Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: linuxsuren
  name: http-downloader-v0.0.53
  namespace: linuxsuren-bot
  selfLink: /apis/devops.kubesphere.io/v1alpha1/namespaces/linuxsuren-bot/releasers/http-downloader-v0.0.53
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/LinuxSuRen/linuxsuren-versions
      branch: master
      name: linuxsuren-versions
      provider: github
    secret: {}
  phase: done
  repositories:
  - action: release
    address: https://github.com/LinuxSuRen/http-downloader
    branch: master
    name: http-downloader
    provider: github
    version: v0.0.53
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.53
status:
  conditions:
  - conditionType: release
    message: https://github.com/LinuxSuRen/http-downloader was released
    status: success
