apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  creationTimestamp: "2022-04-09T14:55:18Z"
  labels:
    app.kubernetes.io/instance: linuxsuren
  name: http-downloader-v0.0.59
  namespace: linuxsuren-bot
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/LinuxSuRen/linuxsuren-versions
      branch: master
      name: linuxsuren-versions
      provider: github
    secret: {}
  phase: draft
  repositories:
  - action: release
    address: https://github.com/LinuxSuRen/http-downloader
    branch: master
    name: http-downloader
    provider: github
    version: v0.0.59
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.59
status: {}
